language: emacs-lisp
sudo: no
env:
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f10f848b8f1ccfc39f77
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install "$EVM_EMACS" --use --skip
install:
  - cask install
script:
  - cask exec buttercup -L . -L tests
branches:
  only:
  - master
  - dev
