language: emacs-lisp
sudo: no
env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=snapshot  
cache:
  - directories:
      # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f10f848b8f1ccfc39f77
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: false
before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - cask install
script:
  - cask exec buttercup -L . -L tests
branches:
  only:
  - master
  - dev
